"""
Markdown export: a human-readable mirror of the memory graph.

Renders ACTIVE facts and rules from the database into a folder of markdown
files — one file per entity, rules in rules.md — so memory can be cat'd,
grep'd, and diff'd. The database remains the source of truth; every
generated file carries a marker header and regeneration removes stale
marker-bearing files (an entity that disappears loses its file).

Deterministic output (sorted entities/attributes, no volatile timestamps
in entity files) keeps diffs meaningful across regenerations.
"""

import json
import os
import re
import sqlite3
from typing import Dict, List, Tuple

MARKER = "<!-- generated by remagent export — do not edit; the database is the source of truth -->"


class ExportError(RuntimeError):
    """Raised when the export cannot be produced; nothing is written."""


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "entity"


def default_out_dir(db_path: str) -> str:
    """memory.db -> <same dir>/memory_md"""
    db = os.path.expanduser(db_path)
    stem = os.path.splitext(os.path.basename(db))[0]
    return os.path.join(os.path.dirname(db) or ".", f"{stem}_md")


def _render_entity(entity_names: List[str], facts: List[dict], agent_id: str) -> str:
    lines = [MARKER, ""]
    for entity in sorted(entity_names):
        lines.append(f"# {entity}")
        lines.append("")
        entity_facts = sorted(
            (f for f in facts if f["entity"] == entity),
            key=lambda f: f["attribute"].lower(),
        )
        for f in entity_facts:
            lines.append(f"## {f['attribute']}")
            lines.append(f"- **Value:** {f['value']}")
            lines.append(f"- **Confidence:** {float(f.get('confidence', 1.0)):.2f}")
            lines.append(f"- **Since:** {f.get('timestamp', 'unknown')}")
            lines.append(f"- **Sources:** {len(f.get('source_turn_ids', []))} turn(s)")
            lines.append("")
    lines.append(f"_Agent: {agent_id}_")
    lines.append("")
    return "\n".join(lines)


def _render_rules(rules: List[dict], agent_id: str) -> str:
    lines = [MARKER, "", "# Operational Rules", ""]
    if not rules:
        lines.append("_No active rules._")
        lines.append("")
    for r in sorted(rules, key=lambda r: (r.get("priority", 3), r.get("rule", "").lower())):
        lines.append(f"## P{r.get('priority', 3)} · {r.get('category', 'operational_directive')}")
        lines.append("")
        lines.append(r.get("rule", ""))
        lines.append("")
        if r.get("rationale"):
            lines.append(f"_Rationale: {r['rationale']}_")
            lines.append("")
    lines.append(f"_Agent: {agent_id}_")
    lines.append("")
    return "\n".join(lines)


def export_markdown(db_path: str, agent_id: str, out_dir: str) -> List[str]:
    """
    Renders the active memory to out_dir. Returns the list of files written.
    Raises ExportError (writing nothing) if the DB or profile is unusable.
    """
    db = os.path.expanduser(db_path)
    out = os.path.expanduser(out_dir)

    if not os.path.exists(db):
        raise ExportError(f"database {db} does not exist")
    try:
        conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
        row = conn.execute(
            "SELECT facts_json, rules_json FROM memory_profiles WHERE agent_id = ?",
            (agent_id,),
        ).fetchone()
        conn.close()
    except Exception as exc:
        raise ExportError(f"cannot read {db}: {exc}") from exc
    if row is None:
        raise ExportError(f"no memory profile found for agent '{agent_id}' in {db}")

    facts = [f for f in json.loads(row[0]) if f.get("is_active")]
    rules = [r for r in json.loads(row[1] or "[]") if r.get("is_active")]

    # Group entities by slug (distinct entities can share a slug; they share
    # a file with separate headings).
    by_slug: Dict[str, List[str]] = {}
    for entity in {f["entity"] for f in facts}:
        by_slug.setdefault(_slugify(entity), []).append(entity)

    # Build every file in memory before touching disk.
    rendered: List[Tuple[str, str]] = [
        (f"{slug}.md", _render_entity(entities, facts, agent_id))
        for slug, entities in sorted(by_slug.items())
    ]
    rendered.append(("rules.md", _render_rules(rules, agent_id)))
    rendered.append((
        "README.md",
        "\n".join([
            MARKER, "",
            "# Memory Mirror", "",
            "Human-readable export of the active RemAgent memory graph — one file",
            "per entity, rules in `rules.md`. **This folder is a mirror, not the",
            "source of truth**: edit nothing here; the database wins and every",
            "dream cycle regenerates these files.", "",
            f"- Agent: `{agent_id}`",
            f"- Database: `{db}`",
            f"- Active facts: {len(facts)} · Active rules: {len(rules)}", "",
        ]),
    ))

    os.makedirs(out, exist_ok=True)

    # Remove stale files WE generated (marker check protects foreign files).
    keep = {name for name, _ in rendered}
    for existing in os.listdir(out):
        path = os.path.join(out, existing)
        if not existing.endswith(".md") or existing in keep or not os.path.isfile(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as fh:
                if fh.readline().strip() == MARKER:
                    os.remove(path)
        except OSError:
            pass

    written = []
    for name, content in rendered:
        path = os.path.join(out, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(path)
    return written
